#257310 Add header to newsletter subscription-page
icmaa/vue-storefront pull request #850
Opened 2022-07-14 08:17 UTC by dlandmann

content is maintained via Storyblok

```
header:
    img: impericon/newsletter/20220713_anmeldeseite_nl_header_en.jpg
    alt: Impericon Newsletter

whys .....
```

## Related ticket

TCK-257310

## Checklist

- [ ] I've made necessary changes in the configs repository `shop-workspace` (if needed)
- [ ] I'm aware of depending changes in other repositories

2022-07-14 08:17 UTC, dlandmann commented
<img width="1471" alt="Bildschirmfoto 2022-07-14 um 09 02 11" src="https://user-images.githubusercontent.com/22610088/178935893-6afa931b-944c-4ef4-bd2d-03b9afc599bc.png">

<img width="615" alt="Bildschirmfoto 2022-07-14 um 09 02 20" src="https://user-images.githubusercontent.com/22610088/178935920-595c9b98-a1c1-4eae-b413-3d0e72f90f2c.png">

2022-07-14 08:37 UTC, cewald requested changes

2022-07-14 08:37 UTC, cewald commented on src/modules/icmaa-newsletter/pages/Newsletter.vue
> +    <div v-if="content.header.img" class="t-container">
Warum nicht die `Picture`-Componente?

2022-07-14 13:14 UTC, dlandmann commented on src/modules/icmaa-newsletter/pages/Newsletter.vue
> +    <div v-if="content.header.img" class="t-container">
ja - d'accord

2022-07-15 05:37 UTC, cewald approved these changes

2022-07-15 05:39 UTC, merged